### ISSUE TITLE
Optics

### ISSUE THREAD

**Issue by truizlop** [arrow-kt/bow#23]
Missing things regarding optics:

- Typeclasses: `At`, `Each`, `FilterIndex`, `Index`
- Optics: `Fold`, `Getter`, `Iso`, `Lens`, `Optional`, `Prism`, `Setter`, `Traversal`
- Laws for all optics

**Comment by RPallas92** [comment]
Reference implementation for [Lens](https://github.com/facile-it/FunctionalKit/blob/master/Sources/FunctionalKit/Lens.swift) and for [Prism](https://github.com/facile-it/FunctionalKit/blob/master/Sources/FunctionalKit/Prism.swift)

**Comment by truizlop** [comment]
#24 implemented `Getter`, `Iso`, `Lens`, `Optional`, `Prism` and `Setter`. Also, all their corresponding laws were included in that PR. Still need to test all their methods though.

**Comment by truizlop** [comment]
#25 implemented `Fold` and `Traversal`, with their corresponding laws.

**Comment by truizlop** [comment]
#26 extends data types with optics.
#27 provides instances for optics.
#28 extends optics typeclasses.
#30 adds tests to optics.
